if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "usage: cmake -DINPUT=<input.b> -DOUTPUT=<output.h> -P embed_bf.cmake")
endif()

file(READ "${INPUT}" _code)
string(REGEX MATCHALL "[><+\\-\\.,\\[\\]]" _tokens "${_code}")
string(JOIN "" _filtered ${_tokens})

set(_out "#ifndef BF_PROGRAM_GENERATED_H\n")
string(APPEND _out "#define BF_PROGRAM_GENERATED_H\n\n")
string(APPEND _out "static const char g_bf_program[] =\n")

string(LENGTH "${_filtered}" _len)
set(_chunk 64)
set(_i 0)
while(_i LESS _len)
    math(EXPR _remain "${_len} - ${_i}")
    if(_remain GREATER _chunk)
        set(_take ${_chunk})
    else()
        set(_take ${_remain})
    endif()
    string(SUBSTRING "${_filtered}" ${_i} ${_take} _part)
    string(APPEND _out "    \"${_part}\"\n")
    math(EXPR _i "${_i} + ${_chunk}")
endwhile()

string(APPEND _out "    ;\n\n")
string(APPEND _out "static const unsigned int g_bf_program_len = sizeof(g_bf_program) - 1;\n\n")
string(APPEND _out "#endif // BF_PROGRAM_GENERATED_H\n")

get_filename_component(_out_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")
file(WRITE "${OUTPUT}" "${_out}")
